language: php

php:
  - "5.6"
  - "5.5"
  - "5.4"

install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y libreoffice-writer"
  - "sudo apt-get install -y unoconv"
  - "composer install"

script: "./vendor/bin/robo test"

cache:
  apt: true